### PR TITLE
Fixed rendering of text about report zipfile contents

### LINKED ISSUE #2399: Incorrect rendering of text about report zipfile contents
- One issue found in https://github.com/kiesraad/abacus/issues/2229

> 1c. De coördinator GSB ontdekt dat een stembureau ten onrechte is meegenomen in een eerdere zitting:
>  1c1. Het GSB maakt een corrigendum naar 0 stemmen voor dit stembureau.
> 1. Onderzoek aangemaakt voor bestaand stembureau
> 2. Overal 0 ingevuld in corrigendum 
> 3. Zitting afgerond
> 4. **Bevinding:** Download pagina geeft aan dat er 1 document in de Zip zit (P 2a). In de werkelijkheid zitten er 3 documenten in (P 2a, Na 14-2 en EML 510b)
> 
> Mogelijk gerelateerd aan:
> 3a. De applicatie stelt vast dat er geen onderzochte stembureaus met gecorrigeerde telresultaten zijn:
>  3a1. De applicatie genereert alleen het PV P 2a (Verslag volgende zitting). 

 _Originally posted by @cikzh in [#2229](https://github.com/kiesraad/abacus/issues/2229#issuecomment-3486461578)_

### PR DESCRIPTION
**Pull request by Lionqueen94**
Closes #2399 

## Description
- Fixed rendering of text about zipfile contents when viewing first session results when there are also second session results
- Fixed rendering of text about zipfile contents when viewing second session results when there are also third session results with a different investigation result
- Fixed copy of file type indicators:
  - EML bestand -> EML-bestand
  - PDF document -> PDF-document
  - Zip bestand -> ZIP-bestand

## Future changes that would be nice, but not to be implemented now
- Change `useInvestigations()` hook to get the investigations from the new investigation list endpoint
- Remove investigations from election details endpoint
- Change the uses of `useElection()` on the investigation pages to use the `useInvestigations()` hook

### CODE REVIEW

File: backend/src/committee_session/api.rs [hunk 1]
```diff
@@ -348,6 +349,41 @@ pub async fn committee_session_status_change(
     Ok(StatusCode::NO_CONTENT)
 }
 
+/// Get a list of all [Investigation]s for a committee session
+#[utoipa::path(
+    get,
+    path = "/api/elections/{election_id}/committee_sessions/{committee_session_id}/investigations",
+    responses(
+        (status = 204, description = "Investigation listing successful", body = InvestigationListResponse),
```
Comment (oliver3) [inline backend/src/committee_session/api.rs]: HTTP status should be 200 when returning something

File: backend/tests/committee_session_integration_test.rs [hunk 2]
```diff
@@ -694,3 +694,75 @@ async fn test_committee_session_number_of_voters_change_not_found(pool: SqlitePo
...
+        .await
+        .unwrap();
+
+    assert_eq!(
+        response.status(),
+        StatusCode::OK,
+        "Unexpected response status"
+    );
+
+    // Validate response and make sure the investigations are from the requested committee session
```
Comment (cikzh) [inline backend/tests/committee_session_integration_test.rs]:
```suggestion
    // Validate response and make sure the investigations are empty
```

File: frontend/src/testing/api-mocks/ElectionMockData.ts [hunk 3]
```diff
@@ -325,6 +326,15 @@ export const getElectionMockData = (
   };
 };
 
+export const getInvestigationMockData = (
+  investigations: PollingStationInvestigation[] = mockInvestigations,
+): Required<InvestigationListResponse> => {
```
Comment (oliver3) [inline frontend/src/testing/api-mocks/ElectionMockData.ts]: No need for [`Required`](https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredtype), there are no optional fields in `InvestigationListResponse`.

File: frontend/src/i18n/locales/nl/election_management.json [hunk 4]
```diff
@@ -28,21 +28,21 @@
...
   "investigation_ordered_by_csb": "Onderzoek in opdracht van het CSB?",
   "lists_and_candidates": "Lijsten en kandidaten",
   "next_session": {
     "with_corrections": {
-      "documents": "<li><strong>Het proces verbaal van het gemeentelijk stembureau (P 2a). Dit is een PDF document.</strong> Dit wordt tijdens de zitting van het gemeentelijk stembureau vastgesteld en ondertekend.</li><li><strong>Het corrigendum van het gemeentelijk stembureau (Na 14-2). Dit is een PDF document.</strong> Bevat de gecorrigeerde telresultaten van de gemeente.</li><li><strong>EML bestand met digitale telresultaten.</strong></li>",
-      "zip_file_explanation": "In het Zip bestand zitten drie documenten:"
+      "documents": "<li><strong>Het proces verbaal van het gemeentelijk stembureau (P 2a). Dit is een PDF-document.</strong> Dit wordt tijdens de zitting van het gemeentelijk stembureau vastgesteld en ondertekend.</li><li><strong>Het corrigendum van het gemeentelijk stembureau (Na 14-2). Dit is een PDF document.</strong> Bevat de gecorrigeerde telresultaten van de gemeente.</li><li><strong>EML-bestand met digitale telresultaten.</strong></li>",
```
Comment (oliver3) [inline frontend/src/i18n/locales/nl/election_management.json]:
```suggestion
      "documents": "<li><strong>Het proces verbaal van het gemeentelijk stembureau (P 2a). Dit is een PDF-document.</strong> Dit wordt tijdens de zitting van het gemeentelijk stembureau vastgesteld en ondertekend.</li><li><strong>Het corrigendum van het gemeentelijk stembureau (Na 14-2). Dit is een PDF-document.</strong> Bevat de gecorrigeerde telresultaten van de gemeente.</li><li><strong>EML-bestand met digitale telresultaten.</strong></li>",
```

**Review by cikzh — CHANGES_REQUESTED** [review]
Only a small thing in a comment to add

File: backend/src/committee_session/api.rs (hunk 1 above)
Comment (Lionqueen94) [reply backend/src/committee_session/api.rs]: Thanks! Fixed in 70231d7fec8613a79c3b10eef8a0b3d62ca882c2

File: frontend/src/testing/api-mocks/ElectionMockData.ts (hunk 3 above)
Comment (Lionqueen94) [reply frontend/src/testing/api-mocks/ElectionMockData.ts]: Good one, fixed in 70231d7fec8613a79c3b10eef8a0b3d62ca882c2

File: frontend/src/i18n/locales/nl/election_management.json (hunk 4 above)
Comment (Lionqueen94) [reply frontend/src/i18n/locales/nl/election_management.json]: :eyes: fixed in 70231d7fec8613a79c3b10eef8a0b3d62ca882c2

File: backend/tests/committee_session_integration_test.rs (hunk 2 above)
Comment (Lionqueen94) [reply backend/tests/committee_session_integration_test.rs]: Fixed in 70231d7fec8613a79c3b10eef8a0b3d62ca882c2

File: frontend/src/i18n/locales/nl/election_management.json [hunk 5]
```diff
@@ -28,21 +28,21 @@
   "enter_a_number": "Voer een getal in",
   "enter_number_of_voters": "Voer het aantal kiesgerechtigden voor deze verkiezing in zoals door de burgemeester en wethouders aan het gemeentelijk stembureau is doorgegeven.",
   "first_session": {
-    "documents": "<li><strong>PDF document met het proces verbaal.</strong> Dit wordt tijdens de zitting van het gemeentelijk stembureau vastgesteld en ondertekend.</li><li><strong>EML bestand met digitale telresultaten.</strong></li>",
-    "zip_file_explanation": "In het Zip bestand zitten twee documenten:"
+    "documents": "<li><strong>PDF-document met het proces verbaal.</strong> Dit wordt tijdens de zitting van het gemeentelijk stembureau vastgesteld en ondertekend.</li><li><strong>EML-bestand met digitale telresultaten.</strong></li>",
```
Comment (lama-d3v) [inline frontend/src/i18n/locales/nl/election_management.json:31]: I don't think the hyphen (`-`) is necessary for `PDF-document` and `EML-bestand`

Comment (Lionqueen94) [reply frontend/src/i18n/locales/nl/election_management.json:31]: According to @marjoleintamis it is :)

Comment (marjoleintamis) [reply frontend/src/i18n/locales/nl/election_management.json:31]: Ja is verplicht! "In samenstellingen met afkortingen in hoofdletters, zoals IRA en NAVO, is het streepje verplicht: IRA-akkoord en NAVO-basis." 

https://onzetaal.nl/taalloket/afkorting-in-samenstelling
