### PR TITLE
Session expiration dialog

### LINKED ISSUE #1138: Make session expiration behavior consistent and user-friendly
The "De sessie is ongeldig" error popup should not be dismissable, as discussed in https://github.com/kiesraad/abacus/pull/964#issuecomment-2704101800. It should also not allow any further interaction with the page, except going to the log in page.

Solution proposed by @jorisleker:
- upon session expiration you are logged out and get redirected to the login page. The login page shows an alert that tells the user they have been logged out because of inactivity
- 10 minutes before your session expires you get a popup with a countdown warning.
- The popup has a button to extend your session. This will hide the popup and reset your session timeout counter

[Design in Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=8680-40548&t=nhDC4RIOVWXTZ7A3-11)

### issue 1: Expired session requires a browser refresh to be able to log in again
Once your session expires and you have unsaved data entry changes, anything you do triggers an API request (either a POST or a DELETE), resulting in an "InvalidSession" error. So you're stuck and the only way out is to refresh the browser.

Steps to reproduce:
1. Fill in some data entry pages.
2. Make a change on the current page. Do not click "Volgende".
3. Wait until your session expires.
4. Do any of the following: click "Inloggen", click "Volgende", navigate to a different data entry page, navigate to the polling station selection page. 
5. The pop-up to save or discard changes appears.
6. Click either button, so either save or discard.
7. An error pop-up appears showing that your session has expired.

### issue 2: Expired session does not block navigation
Without unsaved changes, you can still navigate through the form with the "De sessie is ongeldig" popup showing for each navigation action. See https://github.com/kiesraad/abacus/pull/964#issuecomment-2703461729.

### issue 3: Inconsistent behavior when session expires
Depending on where you are in the application, when your session expires, the application either:
- shows the InvalidSession dialog
- shows an empty page except for the navbar at the top
- redirects to the login page without a message as to why

### PR DESCRIPTION
**Pull request by marlonbaeten**
- More uniform handling of expired sessions or unauthorized routes (redirect to login form + show message)
- Introduce an expiration warning dialog, 10 minutes before the session expires, with a countdown.

Fixes #1138 

To test: login an wait for 20 minutes. Yes this requires some patience, you could change the session life time in `backend/src/authentication/mod.rs` to speed up this process. 

Implementation details:

- Middleware will set the `x-session-expires-at` response header for each authenticated request
- The `ApiProvider` subscribes to this header value which is emitted for the API client and stores the most recent value
- The `AuthorizationDialog` has a timer that checks every second whether the expiration dialog should be shown based on  the current time, the session expiration time and the `EXPIRATION_DIALOG_SECONDS` constant

### CODE REVIEW

**Comment by jschuurk-kr** [comment]
@marlonbaeten Is deleting the session cookie also a valid way to test? Because that's what I've been doing...

**Review by jorisleker — CHANGES_REQUESTED** [review]
- The session expired message on the login page does not match [the design](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=8680-40194&t=hKxpY8jDNsU9JPTW-11)
- I missed the expiration dialog, probably because not every user action leads to a backend request. I had been clicking around using the top level navigation bar (signed in as beheerder). Set a timer for 22 minutes after my last navigation action. And was logged out when returning to the tab after 22 minutes. Expected the dialog.

**Comment by jschuurk-kr** [comment]
Encountering the same issue as @jorisleker with the expiration warning dialog not showing up.

image

image

**Review by jschuurk-kr — DISMISSED** [review]
I can still get the behavior where the "Wat wil je doen met je invoer?"-dialog is shown, then the "Sorry, er ging iets mis"-dialog and I'm not redirected to the login page.

**Comment by marlonbaeten** [comment]
Note that e2e test fail due to the short session lifetime...

File: frontend/app/component/form/account/login/LoginForm.tsx [hunk 1]
```diff
@@ -1,18 +1,34 @@
...
   const [password, setPassword] = useState<string>("");
   const [loading, setLoading] = useState<boolean>(false);
   const [error, setError] = useState<AnyApiError | null>(null);
 
+  // show notification if the user is unauthorized or the session expired
+  let notification: TranslationPath | null = null;
+  if (location.state?.unauthorized === true) {
+    const now = new Date();
+    if (expiration !== null && expiration.getTime() < now.getTime()) {
+      notification = "users.session_expired";
```
Comment (jschuurk-kr) [inline frontend/app/component/form/account/login/LoginForm.tsx:26]: The top navbar does not know the user was logged out
image

File: frontend/app/component/authorization/AuthorizationDialog.tsx [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+    if (!hideDialog && sessionValidFor > 0 && sessionValidFor < EXPIRATION_DIALOG_SECONDS) {
+      return (
+        <Modal
+          title={t("users.expiration_warning")}
+          noFlex={true}
+          onClose={() => {
+            setHideDialog(true);
+          }}
+        >
+          <p>{tx("users.expiration_warning_details", {}, { time: formatTimeToGo(sessionValidFor) })}</p>
```
Comment (jschuurk-kr) [inline frontend/app/component/authorization/AuthorizationDialog.tsx:49]: Nitpick: the countdown numbers are not fixed width, so the "seconden. Niet" on the second line of the text jump back and forth a little when the numbers change.

image

Comment (praseodym) [reply frontend/app/component/authorization/AuthorizationDialog.tsx:49]: Maybe add a line break before "Niet"?

**Comment by jorisleker** [comment]
> Something weird is still going on with unsaved changes. It does the countdown dialog. At the end of the countdown there's briefly no value for the remaining time. Then it shows the "Wat wil je doen met je invoer?" dialog.
> 
> Steps to reproduce:
> 
> 1. Fill in data entry up to the Differences page.
> 2. Return to the Voters and Votes page.
> 3. Change at least one value.
> 4. Wait.

Ran into this at well, without step 1, 2 and 3. Just filled in step 1 and waited on an empty voters and votes page. 

> Nitpick: the countdown numbers are not fixed width, so the "seconden. Niet" on the second line of the text jump back and forth a little when the numbers change.

Can't test now, but was wondering what the copy will be when session expiration is more then 59 seconds away?

**Comment by jschuurk-kr** [comment]
> > Nitpick: the countdown numbers are not fixed width, so the "seconden. Niet" on the second line of the text jump back and forth a little when the numbers change.
> 
> Can't test now, but was wondering what the copy will be when session expiration is more then 59 seconds away?

Based on the code, it should show minutes and seconds, e.g. "1 minuut en 58 seconden".

**Comment by jorisleker** [comment]
> Based on the code, it should show minutes and seconds, e.g. "1 minuut en 58 seconden".

Great, as it should. Can't test it with session expiry set to such a short interval, but let's validate before merge

**Comment by marlonbaeten** [comment]
@jschuurk-kr the issues are fixed - you can test with the short session lifetime on https://regeling-bedoelde-zitting.abacus-test.nl/dev

I'll push the original timeouts and make this PR ready for review again.

**Comment by jschuurk-kr** [comment]
Tested on commit e422af1eb17ed3a01c7331b4acb8568f43c8200c, i.e. without the session timeouts restored. (Hadn't seen [Marlon's comment](https://github.com/kiesraad/abacus/pull/1166#issuecomment-2729759850) yet.)

Previously reported issues are fixed. No new issues found.

If you're logged out while on the /dev page, you are not redirected to the login page, you stay on the /dev page. Definitely a feature, not a bug.

@jorisleker Here's what it looks like when the session expires in more than a minute:
image

**Review by jorisleker — APPROVED** [review]

File: backend/src/authentication/mod.rs [hunk 3]
```diff
@@ -18,10 +18,10 @@ mod user;
 mod util;
 
 /// Session lifetime, for both cookie and database
-pub const SESSION_LIFE_TIME: TimeDelta = TimeDelta::seconds(60 * 30); // 30 minutes
+pub const SESSION_LIFE_TIME: TimeDelta = TimeDelta::seconds(60); // 30 minutes
```
[the remark this answers is not in the document]
Comment (marlonbaeten) [reply backend/src/authentication/mod.rs]: Added

**Review by jorisleker — DISMISSED** [review]

File: frontend/app/component/authorization/AuthorizationDialog.tsx (hunk 2 above)
Comment (marlonbaeten) [reply frontend/app/component/authorization/AuthorizationDialog.tsx]: Added a newline.

**Review by cikzh — APPROVED** [review]

**Review by jorisleker — APPROVED** [review]
