### PR TITLE
Fixed ElectionHomePage, ElectionStatusPage and OverviewPage styling

### LINKED ISSUE #1941: Fix ElectionHomePage, ElectionStatusPage and toolbar styling
### OverviewPage
- Upper padding is too large for typist and coordinator
  - Show toolbar only for administrator

### ElectionStatusPage
- Vertical center alignment for h2+toolbar

### ElectionHomePage
- Remove extra padding in some table rows of election information table

### PR DESCRIPTION
**Pull request by Lionqueen94**
Closes #1941 

## Description
- Removed extra padding in some table rows of `ElectionInformationTable`
- Fixed vertical center alignment for h2 and buttons on `ElectionStatusPage`
- Now showing `Toolbar` on `OverviewPage` only to administrator (removing empty spacing for typist and coordinator)
- Changed `Modal` title from h2 to h3 and added `aria-labelledby`
- Fixed `ErrorModal` styling and added extra margin above nav in `Modal`
- Changed `OverviewPage` title for administrator to `Verkiezingen beheren`
- Changed `PollingStationListPage` title to `Stembureaus beheren`
- Changed `UserListPage` title to `Gebruikers beheren`
- Removed `.tsx/.ts` from imports of election report pages

### CODE REVIEW

File: frontend/src/components/ui/StatusList/StatusList.tsx [hunk 1]
```diff
@@ -22,11 +22,22 @@ export interface StatusListItemProps extends React.HTMLAttributes<HTMLLIElement>
...
+  children,
+  emphasis,
+  padding,
+  smallerMargin,
+  ...props
+}: StatusListItemProps) {
   return (
-    <li className={cn(status, { emphasis: !!emphasis }, { padding: !!padding })} {...props}>
+    <li
+      className={cn(status, { emphasis: !!emphasis }, { padding: !!padding }, { smallerMargin: !!smallerMargin })}
```
Comment (oliver3) [inline frontend/src/components/ui/StatusList/StatusList.tsx]: You can use `smallerMargin && cls.smallerMargin` etc to avoid using `:global()` in the css

File: frontend/src/components/ui/StatusList/StatusList.module.css [hunk 2]
```diff
@@ -31,6 +31,10 @@
       padding-top: 0.5rem;
     }
 
+    &:global(.smallerMargin) {
```
Comment (oliver3) [inline frontend/src/components/ui/StatusList/StatusList.module.css]: No need for global (see comment below) for this and padding, emphasis.

Also, I wonder if padding is still needed, the design does not seem to have this minimal extra padding before the last item:

image

File: frontend/src/components/ui/StatusList/StatusList.tsx (hunk 1 above)
Comment (oliver3) [inline frontend/src/components/ui/StatusList/StatusList.tsx]: One other suggestion would be to change `StatusList` so that it uses flex with gap for the space in between, with a prop e.g. `gap` that is default "md" (corresponding to `--space-md`) but can be set to "sm" for this case

**Review by stacktraceghost — APPROVED** [review]

File: frontend/src/components/ui/StatusList/StatusList.tsx (hunk 1 above)
Comment (Lionqueen94) [reply frontend/src/components/ui/StatusList/StatusList.tsx]: Moved all data entry changes to #1980 and adjusted according to your review

File: frontend/src/components/ui/StatusList/StatusList.module.css (hunk 2 above)
Comment (Lionqueen94) [reply frontend/src/components/ui/StatusList/StatusList.module.css]: True, it seems this was changed, moved all data entry changes to #1980 and adjusted according to your review

File: frontend/src/components/ui/StatusList/StatusList.tsx (hunk 1 above)
Comment (Lionqueen94) [reply frontend/src/components/ui/StatusList/StatusList.tsx]: Moved all data entry changes to #1980 and implemented a gap prop
