### PR TITLE
Fix handling of API errors

### LINKED ISSUE #321: Errors from API are not shown correctly in frontend
Issues with how they are shown:
1. Both the 4xx and 5xx range are showns as "Server error".
2. The specifics of the error response are not shown on the screen, only the `:` is shown.

There are two options to solve issue 1:
- distinguish Client errors from Server errors
- call them all Errors, because the distinction is not helpful to our users

image

We should change the API client code to return a better error object (maybe something like the [Rust `Result` type but in TypeScript](https://imhoff.blog/posts/using-results-in-typescript)?). The `Feedback` component should render this correctly, preferably by passing down the error object in a new prop instead of using the current `data` prop for both validation results (errors and warnings) and API errors.

### PR DESCRIPTION
**Pull request by praseodym**
Fixes #321

### CODE REVIEW

**Review by Lionqueen94 — DISMISSED** [review]

File: frontend/app/component/form/pollingstation_save/PollingStationSaveForm.tsx
Comment (jschuurk-kr) [inline frontend/app/component/form/pollingstation_save/PollingStationSaveForm.tsx:1]: The "Controleren en opslaan" page does not scroll up automatically when there's an API error. This behavior is relevant if there are enough lists with zero votes that you do need to scroll down to the "Opslaan" button.

File: frontend/app/component/pollingstation/PollingStationFormNavigation.tsx [hunk 1]
```diff
@@ -152,7 +152,7 @@ export function PollingStationFormNavigation({ pollingStationId, election }: Pol
         </Modal>
       )}
 
-      {error && <Feedback id="feedback-server-error" type="error" data={error} />}
+      {apiError && <Feedback id="feedback-server-error" type="error" apiError={apiError} />}
```
Comment (jschuurk-kr) [inline frontend/app/component/pollingstation/PollingStationFormNavigation.tsx:155]: It would be nice to have some whitespace below this error message.
image

Comment (jschuurk-kr) [inline frontend/app/component/pollingstation/PollingStationFormNavigation.tsx:155]: Once this kind of error is shown, it's shown on all pages. It also does not go away after a succesful submit.

Tested by making the finalise endpoint return a 500 response.

File: frontend/app/component/form/pollingstation_save/PollingStationSaveForm.tsx
Comment (praseodym) [reply frontend/app/component/form/pollingstation_save/PollingStationSaveForm.tsx:1]: Fixed in 28bbd0eb6e08faade61173208947eb0a39df4344.

File: frontend/app/component/pollingstation/PollingStationFormNavigation.tsx (hunk 1 above)
Comment (praseodym) [reply frontend/app/component/pollingstation/PollingStationFormNavigation.tsx:162]: Fixed in 0c1467b884c6e32855ef6188c5cf8a793ed93650.

**Review by jschuurk-kr — APPROVED** [review]
