### PR TITLE
Fix button styling and added icon

### LINKED ISSUE #1756: Fix button width
Figma:
Image

This PR:
Image

_Originally posted by @praseodym in https://github.com/kiesraad/abacus/pull/1667#pullrequestreview-3000324368_

### PR DESCRIPTION
**Pull request by bramtweedegolf**
The .lg button class was given a min-width of 13rem. 

As a result many buttons are wider than the design, such as the login page.

On main:

Screenshot_2025-07-21_13-45-31

Design:

Screenshot_2025-07-21_13-51-28

The same goes for most buttons for data entry.

On main:

Screenshot_2025-07-21_13-45-46

Design:

Screenshot_2025-07-21_13-37-48

This commit fixes the width of these buttons.

Only the modal buttons should have min-width, so I added a class .xl (should maybe be renamed to extra-wide or something more descriptive?) used only on the modal buttons.

I also added a missing icon for two modal buttons:

Screenshot_2025-07-21_13-43-08

Fixes #1756

### CODE REVIEW

**Comment by bramtweedegolf** [comment]
> @bramtweedegolf thanks for noticing. The label of the 'Beginnen' button on PollingStationChoice was changed to 'Volgende' by accident in Figma. I've reverted that to 'Beginnen'. Can you update your PR?

@jorisleker The description of my PR was a bit misleading; I only changed the width of the buttons. I did not touch the label of the button, so it is still 'Beginnen'.

File: frontend/src/features/election_create/components/AbortModal.tsx [hunk 1]
```diff
@@ -71,6 +71,7 @@ export function AbortModal() {
           {t("election.abort.discard_input")}
         </Button>
         <Button
+          size="lg"
```
Comment (Lionqueen94) [inline frontend/src/features/election_create/components/AbortModal.tsx:74]: Shouldn't the button on the modal be size xl?

**Review by jorisleker — DISMISSED** [review]

**Comment by bramtweedegolf** [comment]
Thanks @Lionqueen94  and @oliver3 for the thorough testing! 

I changed the classes to xl for:

- AbortModal (only the confirm button, the cancel button is not wide according to the design)
- Modal in DataEntryNavigation
- Modal in the modal stories to give the good example

Changed in [dea29f4](https://github.com/kiesraad/abacus/pull/1808/commits/dea29f4dc528ce3f1791fdd30c3580ab1fb0b88f)

**Review by oliver3 — APPROVED** [review]

**Review by oliver3 — APPROVED** [review]

**Review by Lionqueen94 — APPROVED** [review]
