### PR TITLE
Fix flaky test 'OverviewPage > Renders elections for typist'

### LINKED ISSUE #2044: Refresh elections overview page every x seconds
> Maybe refreshing the elections overview page every x seconds, like we did [for the elections status page](https://github.com/kiesraad/abacus/pull/1924) would alleviate both issues @jschuurk-kr  @jorisleker ?

_Originally posted by @oliver3 in https://github.com/kiesraad/abacus/issues/1928#issuecomment-3182524534_

### PR DESCRIPTION
**Pull request by Lionqueen94**
Flaky test should be fixed now and elections still get refetched when clicking "Naar startscherm" on the CommitteeSessionPaused modal.
- Removed `ElectionListProvider` in favor of a get request in the `OverviewPage` directly
- Also added the get request for elections to `DevHomePage`
- Also added an every 30s refetch for `OverviewPage` (resolves #2044)

### CODE REVIEW

**Review by stacktraceghost — DISMISSED** [review]

File: frontend/src/features/election_create/components/CheckAndSave.tsx [hunk 1]
```diff
@@ -40,8 +38,6 @@ export function CheckAndSave() {
         type: "RESET",
       });
 
-      // update stored elections
-      await refetch();
```
Comment (Lionqueen94) [inline frontend/src/features/election_create/components/CheckAndSave.tsx:44]: Not having this refetch now causes the navigate to elections not to happen, do you have any suggestion how to tackle this @praseodym

**Review by oliver3 — APPROVED** [review]

**Review by stacktraceghost — APPROVED** [review]
